[package]
name = "rvp"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/samgozman/rvp"
repository = "https://github.com/samgozman/rvp"
authors = ["Sam Gozman <sam@gozman.space>"]
description = "Remote Value Parser - CLI tool for parsing string values from static web pages"
keywords = ["rvp", "parser", "cli"]
rust-version = "1.68.0"
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
anyhow = "1.0.69"
paste = "1.0.12"
tokio = { version = "1.26.0", features = ["full"] }
