[package]
name = "rvp"
version = "0.1.3"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/samgozman/rvp"
repository = "https://github.com/samgozman/rvp"
authors = ["Sam Gozman <sam@gozman.space>"]
description = "Remote Value Parser - CLI tool for parsing string values from static web pages"
keywords = ["rvp", "parser", "cli"]
rust-version = "1.68.0"
include = ["src/**/*", "LICENSE", "README.md"]

[[bin]]
name = "rvp"
path = "src/main.rs"

[profile.release]
lto = true
strip = true

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
anyhow = "1.0.71"
paste = "1.0.12"
tokio = { version = "1.28.1", features = ["test-util", "macros", "rt-multi-thread"] }
validator = { version = "0.16.0", features = ["derive"] }
reqwest = "0.11.18"
scraper = "0.16.0"
inquire = "0.6.2"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
serde_json = "1.0.95"
rand = "0.8.5"
comfy-table = "6.1.4"
regex = "1.8.1"
