on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

name: CI

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: 1.68.0
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check

  clippy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.6
        with:
          components: clippy
          toolchain: 1.68.0
      - name: Run clippy
        run: cargo clippy --locked --all-targets --all-features --workspace -- -D warnings

  # TODO: Tests
  # TODO: Build
  # TODO: Release

  conclusion:
    needs: [fmt, clippy]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Result
        run: |
          jq -C <<< "${needs}"
          # Check if all needs were successful or skipped.
          "$(jq -r 'all(.result as $result | (["success", "skipped"] | contains([$result])))' <<< "${needs}")"
        env:
          needs: ${{ toJson(needs) }}
